kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
    - hostPath: audit-policy/
      containerPath: /etc/kubernetes/audit
      readOnly: true
    - hostPath: mnt/kind-control-plane/audit
      containerPath: /var/log/kubernetes
      readOnly: false
    - hostPath: mnt/kind-control-plane/containers
      containerPath: /mnt/log
      readOnly: false
  kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        audit-policy-file: "/etc/kubernetes/audit/audit-policy.yaml"
        audit-log-path: "/var/log/kubernetes/audit.log"
        audit-log-maxage: "30"
        audit-log-maxbackup: "10"
        audit-log-maxsize: "100"
      extraVolumes:
        - name: audit-config
          hostPath: /etc/kubernetes/audit
          mountPath: /etc/kubernetes/audit
          readOnly: true
          pathType: Directory
        - name: audit-logs
          hostPath: /var/log/kubernetes
          mountPath: /var/log/kubernetes
          readOnly: false
          pathType: DirectoryOrCreate
  - |
    kind: KubeletConfiguration
    metadata:
      name: config
    apiVersion: kubelet.config.k8s.io/v1beta1
    logging:
      format: json  
- role: worker
  extraMounts:
    - hostPath: mnt/kind-worker/containers
      containerPath: /mnt/log
      readOnly: false
  kubeadmConfigPatches:
  - |
    kind: KubeletConfiguration
    metadata:
      name: config
    apiVersion: kubelet.config.k8s.io/v1beta1
    logging:
      format: json
- role: worker
  extraMounts:
    - hostPath: mnt/kind-worker2/containers
      containerPath: /mnt/log
      readOnly: false
  kubeadmConfigPatches:
  - |
    kind: KubeletConfiguration
    metadata:
      name: config
    apiVersion: kubelet.config.k8s.io/v1beta1
    logging:
      format: json
- role: worker
  extraMounts:
    - hostPath: mnt/kind-worker3/containers
      containerPath: /mnt/log
      readOnly: false
  kubeadmConfigPatches:
  - |
    kind: KubeletConfiguration
    metadata:
      name: config
    apiVersion: kubelet.config.k8s.io/v1beta1
    logging:
      format: json
